In [1]:
%load_ext autotime
#pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [1]:
import ipywidgets as widgets
import difflib

In [20]:

w = widgets.Textarea(
    value='',
    placeholder='Type something',
    description='Skill:',
    disabled=False,
    tooltip='Enter the name of the Text field'
)

display(w)

def print_text(widget):
    old_input = widget['old']
    new_input = widget['new']
    # In questo modo però si cattura solo l'ultimo carattere inserito, trovare un modo più intelligente di 
    # dividere la sottoparola che si sta inserendo da quelle già inserite
    new_skill = ''.join([li.split('+ ')[-1] for li in difflib.ndiff(old_input, new_input) if li[0] != ' '])
    print(new_skill)

w.observe(print_text, names='value')

Textarea(value='', description='Skill:', placeholder='Type something')

ciao mamma
 
d
a
t
a


## Prove con il calcolo della matrice di similarità 

In [16]:
import io
import fasttext
import numpy as np
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
# define training data
sentences = [['this', 'is', 'the', 'first', 'sentence', 'for', 'word2vec'],
             ['this', 'is', 'the', 'second', 'sentence'],
             ['yet', 'another', 'sentence'],
             ['one', 'more', 'sentence'],
             ['and', 'the', 'final', 'sentence']]
# train model
model = Word2Vec(sentences, min_count=1)
# summarize the loaded model
print(model)
# summarize vocabulary
words = list(model.wv.vocab)
print(words)
# access vector for one word
print(model['sentence'])

Word2Vec(vocab=14, size=100, alpha=0.025)
['this', 'is', 'the', 'first', 'sentence', 'for', 'word2vec', 'second', 'yet', 'another', 'one', 'more', 'and', 'final']
[ 3.9038677e-03  2.1353054e-03 -1.4082966e-03  2.0365366e-03
 -3.5627359e-03 -1.8132008e-03 -4.0954417e-03 -9.4652449e-04
 -5.6126395e-05 -1.9248931e-03  4.1233641e-03 -2.3521865e-03
 -1.5022117e-03 -4.5918180e-03 -2.7790943e-03  3.9335280e-03
 -3.2057122e-03  1.5088647e-03  9.2934242e-05  4.5545478e-03
  4.2981198e-03 -4.2119706e-03  4.4398233e-03  1.4217990e-03
 -1.3089800e-03  2.0811174e-03  3.9092861e-03 -1.5299969e-03
 -2.5253422e-03  3.2367893e-03 -2.0729811e-03  2.1194087e-03
 -1.0372913e-03 -8.7570236e-04  3.7507717e-03 -4.2750160e-03
 -2.8764897e-03 -2.2837380e-03  4.5618149e-03  3.5065724e-04
 -7.7784987e-04 -1.4684200e-03  3.5635368e-03 -6.4966921e-04
  3.5933470e-03  4.0631113e-03 -3.6892453e-03  9.9984456e-05
  3.0918941e-03 -1.2781309e-03 -1.3956561e-03  7.0078924e-05
 -4.8584035e-03  1.4186430e-03  2.9012910e-0

/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:15: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  from ipykernel import kernelapp as app


In [18]:
new_model.wv.syn0.T

/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  """Entry point for launching an IPython kernel.


array([[ 3.9038677e-03,  2.3776710e-03, -4.8592724e-04, ...,
         5.8666884e-04, -1.3089438e-03,  9.6065871e-04],
       [ 2.1353054e-03, -3.3927802e-04,  5.0889113e-04, ...,
         3.6292754e-03, -4.6689552e-03, -4.2265970e-03],
       [-1.4082966e-03,  4.1139419e-03,  3.4382371e-03, ...,
         4.4263555e-03,  4.4938163e-03, -4.9103112e-03],
       ...,
       [-1.0271526e-03, -2.3557281e-03,  1.7790480e-03, ...,
         4.4807680e-03,  2.5828418e-03,  2.3941048e-04],
       [ 2.4120021e-03,  2.5451963e-03,  9.5552066e-05, ...,
         2.3635160e-03,  2.4734442e-03,  1.9027404e-03],
       [-1.8412314e-03, -1.8158141e-03,  1.3591807e-03, ...,
        -3.5341408e-03,  4.3473043e-03, -4.9680928e-03]], dtype=float32)

In [30]:
M = gensim.similarities.MatrixSimilarity(gensim.matutils.Dense2Corpus(new_model.wv.vectors))

In [50]:
new_model[list(new_model.wv.vocab)][0]

/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([-4.8592724e-04,  5.0889113e-04,  3.4382371e-03,  1.8026620e-03,
       -3.6679306e-03, -2.9366417e-03, -4.3747742e-03, -3.3037667e-03,
       -8.2607585e-05,  4.8255734e-03,  1.7213918e-03, -2.7898313e-03,
        4.2465255e-03,  3.7324559e-03,  1.8495247e-03, -2.0346513e-03,
        2.4053338e-03,  2.6409116e-03,  6.1205843e-05, -2.3018897e-03,
       -4.8005683e-03,  8.4636058e-04,  9.3633047e-04, -3.7659642e-03,
        1.5389281e-03,  2.2728508e-03,  4.5305141e-03, -3.9770859e-03,
       -3.9078277e-03,  1.4007512e-03,  8.1961497e-04,  2.6625600e-03,
       -4.6308585e-03,  5.7140930e-04,  1.0644670e-03,  1.6245897e-03,
        2.1110939e-04, -4.2086322e-04,  1.9440008e-03, -2.6336473e-03,
       -4.2530671e-03, -4.3738768e-03,  1.2523547e-04,  1.8110209e-03,
       -4.3476340e-03, -3.6855834e-03, -2.1644779e-03,  4.1131317e-03,
        4.0775877e-03, -2.3671405e-03,  2.8593864e-03, -5.7597208e-05,
        4.7869459e-03,  7.0393807e-04,  1.5120321e-03, -3.1455269e-03,
      

In [34]:
result = model.most_similar('first')
print(result)

[('final', 0.15972749888896942), ('one', 0.1229441836476326), ('another', 0.05594411492347717), ('more', 0.03111601062119007), ('this', 0.004960008896887302), ('is', -0.03630427271127701), ('and', -0.06384521722793579), ('second', -0.08091191947460175), ('word2vec', -0.08727197349071503), ('sentence', -0.08728539198637009)]
time: 2.17 ms


/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


In [42]:

matrix = np.dot(model.wv.syn0norm, model.wv.syn0norm.T)

time: 3.71 ms


/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0norm` (Attribute will be removed in 4.0.0, use self.vectors_norm instead).
  """Entry point for launching an IPython kernel.


In [50]:
from gensim.similarities import MatrixSimilarity

m2 = gensim.similarities.MatrixSimilarity(gensim.matutils.Dense2Corpus(model.wv.syn0))

time: 10.7 ms


/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [59]:
similarity_array[1,2]

-0.15163246

time: 5.45 ms


In [54]:
similarity_matrix = []
for sims in m2:
    similarity_matrix.append(sims)
similarity_array = np.array(similarity_matrix)

time: 1.31 ms


In [64]:
aa = gensim.similarities.MatrixSimilarity(gensim.matutils.Dense2Corpus(model.wv.syn0.T))

time: 4 ms


/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  """Entry point for launching an IPython kernel.


In [104]:
aa.get_similarities([(15, 15), (15, 15)])

array([-0.53032404,  2.4504747 ,  2.2034955 ,  1.996935  , -1.3378329 ,
       -2.2813873 , -2.308627  , -1.6702954 , -1.5804367 , -1.352123  ,
        2.3730109 , -0.74854577,  1.3990581 ,  2.2709007 ], dtype=float32)

time: 3.77 ms


In [63]:
from scipy.spatial.distance import cdist
similarity =cdist(model.wv.syn0, model.wv.syn0, metric='cosine')

similarity # similarity between 'cat' and 'dog'

/home/simone/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  


array([[0.00000000e+00, 1.21335549e+00, 9.40977823e-01, 1.08805909e+00,
        1.08728540e+00, 1.15372349e+00, 1.00019432e+00, 9.11463861e-01,
        1.14807783e+00, 1.12895675e+00, 1.04260360e+00, 8.98144074e-01,
        9.44486713e-01, 1.00164575e+00],
       [1.21335549e+00, 1.11022302e-16, 1.10564366e+00, 1.03864117e+00,
        1.09148205e+00, 7.99665101e-01, 1.00671258e+00, 9.77943590e-01,
        9.25224036e-01, 9.93878060e-01, 8.33491799e-01, 9.76038717e-01,
        8.59558384e-01, 8.87739669e-01],
       [9.40977823e-01, 1.10564366e+00, 0.00000000e+00, 1.00711268e+00,
        9.95039993e-01, 1.09107015e+00, 9.41347900e-01, 1.13173356e+00,
        1.30386453e+00, 1.01109328e+00, 9.75911261e-01, 9.56103865e-01,
        8.38175099e-01, 1.08094627e+00],
       [1.08805909e+00, 1.03864117e+00, 1.00711268e+00, 0.00000000e+00,
        1.03630427e+00, 1.10631974e+00, 8.06871905e-01, 1.11938166e+00,
        9.56457088e-01, 1.09926944e+00, 1.06633042e+00, 1.05628416e+00,
        8.640

time: 11.1 ms
